language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jorge00alves/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jorge00alves/docker-react npm run test
